import type { Metadata } from "next";

// 전역 CSS
import "./styles/globals.css";

// Components
import SideNavigation from "@/components/common/navigation/SideNavigation";

// Shadcn UI
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SideNavigation />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
